#!/usr/bin/env bash
#check if there are 4 arguements 
if["#$" -lt 4]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi 
# Construct the server host address
host="$3@$2:~/"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$host"